adb devices 
adb shell pm uninstall --user 0 com.samsung.android.app.episodes
adb shell pm uninstall --user 0 com.samsung.android.app.storyalbumwidget
adb shell pm uninstall --user 0 com.samsung.android.beaconmanager
adb shell pm uninstall --user 0 com.android.noisefield
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.sec.android.widgetapp.webmanual
adb shell pm uninstall --user 0 com.sec.chaton
adb shell pm uninstall --user 0 com.sec.android.widgetapp.dualclockdigital
adb shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb shell pm uninstall --user 0 com.sec.android.cloudagent
adb shell pm uninstall --user 0 com.sec.kidsplat.installer
adb shell pm uninstall --user 0 com.android.backupconfirm
adb shell pm uninstall --user 0 com.android.browser.provider
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.dsi.ant.plugins.antplus
adb shell pm uninstall --user 0 com.dsi.ant.service.socket
adb shell pm uninstall --user 0 com.samsung.android.widgetapp.briefing4x2
adb shell pm uninstall --user 0 com.blurb.checkout
adb shell pm uninstall --user 0 com.samsung.android.sdk.spenv10
adb shell pm uninstall --user 0 com.monotype.android.font.chococooky
adb shell pm uninstall --user 0 com.sec.android.app.minimode.res
adb shell pm uninstall --user 0 com.sec.android.app.tourviewer
adb shell pm uninstall --user 0 com.dsi.ant.server
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
adb shell pm uninstall --user 0 com.diotek.diodict3.service
adb shell pm uninstall --user 0 com.sec.android.directconnect
adb shell pm uninstall --user 0 com.arcsoft.picaction.app
adb shell pm uninstall --user 0 com.sec.dsm.system
adb shell pm uninstall --user 0 com.sec.android.diagmonagent
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.dropbox.android
adb shell pm uninstall --user 0 com.sec.android.cloudagent.dropboxoobe
adb shell pm uninstall --user 0 com.android.email
adb shell pm uninstall --user 0 com.sec.esdk.elm
adb shell pm uninstall --user 0 com.sec.android.app.safetyassurance
adb shell pm uninstall --user 0 com.arcsoft.picturesbest.app
adb shell pm uninstall --user 0 com.android.exchange
adb shell pm uninstall --user 0 com.sec.android.widgetapp.easyfavoritescontactswidget
adb shell pm uninstall --user 0 flipboard.app
adb shell pm uninstall --user 0 com.android.dreams.phototable
adb shell pm uninstall --user 0 com.sec.android.app.GlanceView
adb shell pm uninstall --user 0 com.google.android.gm
adb shell pm uninstall --user 0 com.google.android.apps.plus
adb shell pm uninstall --user 0 com.google.android.backuptransport
adb shell pm uninstall --user 0 com.google.android.gsf.login
adb shell pm uninstall --user 0 com.google.android.gsf
adb shell pm uninstall --user 0 com.google.android.syncadapters.contacts
adb shell pm uninstall --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.apps.magazines
adb shell pm uninstall --user 0 com.google.android.apps.books
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.play.games
adb shell pm uninstall --user 0 com.android.vending
adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.android.chrome
adb shell pm uninstall --user 0 com.google.android.gms
adb shell pm uninstall --user 0 com.samsung.groupcast
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.arcsoft.picmovie
adb shell pm uninstall --user 0 com.sec.android.widgetapp.ap.hero.accuweather
adb shell pm uninstall --user 0 com.sec.android.service.health
adb shell pm uninstall --user 0 com.android.providers.downloads.ui
adb shell pm uninstall --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall --user 0 com.android.phasebeam
adb shell pm uninstall --user 0 com.samsung.klmsagent
adb shell pm uninstall --user 0 com.sec.knox.setupwizardstub
adb shell pm uninstall --user 0 com.sec.knox.store
adb shell pm uninstall --user 0 com.sec.knox.bridge
adb shell pm uninstall --user 0 com.sec.knox.switchknoxI
adb shell pm uninstall --user 0 com.sec.knox.switchknoxII
adb shell pm uninstall --user 0 com.sec.knox.containeragent
adb shell pm uninstall --user 0 com.sec.knox.knoxsetupwizardclient
adb shell pm uninstall --user 0 com.sec.android.app.collage
adb shell pm uninstall --user 0 com.LocalFota
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.sec.android.mmapp
adb shell pm uninstall --user 0 com.sec.android.app.music
adb shell pm uninstall --user 0 com.sec.android.app.mediasync
adb shell pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
adb shell pm uninstall --user 0 com.sec.android.pagebuddynotisvc
adb shell pm uninstall --user 0 com.samsung.android.personalpage.service
adb shell pm uninstall --user 0 com.infraware.polarisviewer5
adb shell pm uninstall --user 0 com.samsung.android.sconnect
adb shell pm uninstall --user 0 com.monotype.android.font.rosemary
adb shell pm uninstall --user 0 com.osp.app.signin
adb shell pm uninstall --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall --user 0 com.sec.android.app.billing
adb shell pm uninstall --user 0 com.samsung.android.scloud.proxy.calendar
adb shell pm uninstall --user 0 com.samsung.android.scloud.auth
adb shell pm uninstall --user 0 com.samsung.android.scloud.quota
adb shell pm uninstall --user 0 com.samsung.android.scloud.proxy.contacts
adb shell pm uninstall --user 0 com.sec.android.app.sns3
adb shell pm uninstall --user 0 com.sec.android.widget.samsungapps
adb shell pm uninstall --user 0 com.sec.android.app.gamehub
adb shell pm uninstall --user 0 com.sec.everglades
adb shell pm uninstall --user 0 com.sec.everglades.update
adb shell pm uninstall --user 0 com.sec.pcw
adb shell pm uninstall --user 0 com.samsung.android.sdk.samsunglink
adb shell pm uninstall --user 0 com.sec.msc.nts.android.proxy
adb shell pm uninstall --user 0 com.sec.app.samsungprintservice
adb shell pm uninstall --user 0 com.sec.spp.push
adb shell pm uninstall --user 0 com.monotype.android.font.samsungsans
adb shell pm uninstall --user 0 com.samsung.android.scloud.proxy.sbrowser
adb shell pm uninstall --user 0 com.samsung.android.scloud.proxy.snote
adb shell pm uninstall --user 0 com.samsung.android.scloud.proxy.snote3
adb shell pm uninstall --user 0 com.samsung.android.scloud.sync
adb shell pm uninstall --user 0 com.sec.android.directshare
adb shell pm uninstall --user 0 com.sec.android.app.translator
adb shell pm uninstall --user 0 com.samsung.android.tripwidget
adb shell pm uninstall --user 0 com.samsung.android.service.travel
adb shell pm uninstall --user 0 com.samsung.android.app.galaxyfinder
adb shell pm uninstall --user 0 com.sec.android.app.shealth
adb shell pm uninstall --user 0 com.arcsoft.demo.piclear
adb shell pm uninstall --user 0 com.sec.android.provider.snote
adb shell pm uninstall --user 0 com.sec.android.widgetapp.diotek.smemo
adb shell pm uninstall --user 0 com.vlingo.midas
adb shell pm uninstall --user 0 com.sec.android.inputmethod
adb shell pm uninstall --user 0 com.sec.android.app.SecSetupWizard
adb shell pm uninstall --user 0 com.sec.android.motions.settings.airmotiontutorial
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.tripadvisor.tripadvisor
adb shell pm uninstall --user 0 com.sec.android.app.easylauncher
adb shell pm uninstall --user 0 com.sec.android.daemonapp
adb shell pm uninstall --user 0 com.sec.android.widgetapp.ap.yahoostock.stockclock
adb shell pm uninstall --user 0 com.sec.android.widgetapp.ap.yahoonews
adb shell pm uninstall --user 0 com.samsung.android.nearby.mediaserver
adb shell pm uninstall --user 0 com.samsung.android.scloud.backup
adb shell pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
adb shell pm uninstall --user 0 com.google.android.youtube
adb shell pm uninstall --user 0 com.samsung.helphub
adb shell pm uninstall --user 0 com.wssyncmldm
adb shell pm uninstall --user 0 tv.peel.samsung.app
adb shell pm uninstall --user 0 com.samsung.everglades.video
adb shell pm uninstall --user 0 com.sec.android.app.mv.player
adb shell pm uninstall --user 0 com.sec.android.fotaclient
adb shell pm uninstall --user 0 deezer.android.app
adb shell pm uninstall --user 0 com.deezer.android.partner
adb shell pm uninstall --user 0 com.sec.android.app.sbrowsertry
adb shell pm uninstall --user 0 com.sec.hearingadjust
adb shell pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
adb install .\APK\AuroraStore.apk
adb install .\APK\Keyboard.apk
adb install .\APK\SD_Maid.apk
pause
adb reboot